### ISSUE TITLE
Cannot Add New Configuration

### ISSUE THREAD

**Issue by gorino** [basetime/bldr-sfmc#33]
## Setup

1. I created the package with the proper permissions and enabling for all business units: 
<img width="397" alt="package-permissions" src="https://user-images.githubusercontent.com/5113069/193629501-114177b2-a176-4b9d-8c31-5cfe09a4a04e.png">

2. Running `bldr config -l -d` shows "There are no Configured Instances" message as the config is not saved

3. Running `bldr status` shows "allowTracking true" under Current Status and "No Files Staged" under Staged Files as the config is not saved

---

### Expected Behavior

I expect to add a new configuration running `bldr config -n` and adding the proper details.

### Steps to Reproduce

1. Run `bldr config -n`
2. Set Instance Name equal to `Source Account` in the package details page
3. Set Parent MID equal to `MID` of the parent business unit
4. Set API Client ID equal to `Client Id` in the package details page
5. Set API Client Secret equal to `Client Secret` in the package details page
6. Set Authentication URI equal to `Authentication Base URI ` in the package details page

<img width="933" alt="bldr-sfmc-config" src="https://user-images.githubusercontent.com/5113069/193630615-3270a04f-67d5-4179-909c-517f0934087e.png">

### Additional Context

Work with MacOS 11.6.8, iTerm 3.4.16 and zsh 5.8 (x86_64-apple-darwin20.0)
`node` installed via Homebrew
`libsecret` installed via Homebrew prior to `bldr`

**Comment by anthonymzupancic** [comment]
I'll take a look at this and reply once I have some insights!

**Comment by anthonymzupancic** [comment]
@gorino  thanks for the catch, I updated the main CLI index file and I must have removed a function that sets up for the encryption. 

I'll patch this real quick tonight and post back here.

**Comment by anthonymzupancic** [comment]
@gorino found the issue, there was an issue where my encryption setup was being called before the function was declared. Made some adjustments, re-tested and should work as expected.

Please take the following actions:
- `npm update -g @basetime/bldr-sfmc`
- `bldr -v` => should return "bldr version: 1.5.15"
- Retry setting your configuration

**Comment by gorino** [comment]
@anthonymzupancic thanks for your help! I am trying to update with no success.

- run `npm update -g @basetime/bldr-sfmc` results in "bldr version: 1.5.14"
- tried uninstall / install, still getting 1.5.14

**Comment by anthonymzupancic** [comment]
@gorino Thanks for bearing with me trying to figure this out!
I updated the package on my personal mac and saw the same results. 

I re-published the package just now and ran `npm update -g @basetime/bldr-sfmc` and it seems to have worked.
I also removed all of my previous configuration entries and tested `bldr config -n` and was able to successfully save the credentials.

Please re-run the update command and see if it updates/works now.

**Comment by gorino** [comment]
It works!
Thank you so much @anthonymzupancic for your quick support, really appreciated.

**Comment by anthonymzupancic** [comment]
For sure!

Feel free to reach out again if you run into any additional bugs.
Not sure if you are part of the Email Geeks Slack group (email.geeks.chat) but would love to know what you think of bldr!
