### ISSUE TITLE
getAllBusinessUnitDetails.map is not a function

### ISSUE THREAD

**Issue by emark-wtcx** [basetime/bldr-sfmc#35]
Hi guys, first of all, great concept. I've been meaning to try this out for a while now, finally got around to trying it out but I'm having issue on config creation. 

Upon successfully entering all of the requested information, I am presented with the error:

getAllBusinessUnitDetails.map is not a function

As this is the first configuration, my initial thought is that it seems like there's a missing check involved, but being that other users have been able to successfully setup the first config I'm obviously overlooking something with that determination.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/117347134/212686029-8318e381-de72-40bd-ad4d-bc742acb876b.png">

Any ideas?

**Comment by anthonymzupancic** [comment]
Thanks for your interest in bldr, and submitting the issue!


I'm currently out of the office today but I'll look into it tomorrow morning and reply back.

In the mean time, can you do me a favor and let me know if:

- You're using server to server or web app authentication
- verify that your scope matches the documentation
